server:
  port: 8081
spring:
  profiles:
    active: prod
  application:
    name: dlut-eda-mcp
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: DLUT-EDA_MCP
        type: ASYNC

mybatis:
  mapper-locations: classpath:mapper/*.xml # 指定SQL映射文件的位置
  configuration:
    map-underscore-to-camel-case: true # 开启下划线转驼峰命名

feign:
  spi: https://xc.linyang.ink/