spring:
  application:
    name: dlut-eda-mcp
  main:
    banner-mode: off
  datasource:
    # 请在.env中配置数据库连接信息
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    mcp:
      server:
        name: DLUT-EDA_MCP
        type: ASYNC
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 5000
      username: ${REDIS_USERNAME}

redisson:
  config: |
    singleServerConfig:
      address: "redis://root:7539518426@192.168.124.4:6379"
      password: "7539518426"
      timeout: 5000
      connectionPoolSize: 64
      connectionMinimumIdleSize: 10
    threads: 16
    nettyThreads: 32


#logging:
#  pattern:
#    console:

mybatis:
  mapper-locations: classpath:mapper/*.xml # 指定SQL映射文件的位置
  configuration:
    map-underscore-to-camel-case: true # 开启下划线转驼峰命名
